<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="prometheus-net.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AzKotle.Application\AzKotle.Application.csproj" />
    <ProjectReference Include="..\AzKotle.Infrastructure\AzKotle.Infrastructure.csproj" />
    <ProjectReference Include="..\AzKotle.Shared\AzKotle.Shared.csproj" />
  </ItemGroup>

</Project>
