// <auto-generated />
using System;
using AzKotle.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AzKotle.Web.Data.Migrations
{
    [DbContext(typeof(AzKotleDbContext))]
    partial class AzKotleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AzKotle.Core.Entities.Kotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Palivo")
                        .HasColumnType("integer");

                    b.Property<int?>("RokVyroby")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Umisteni")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VlastnikEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VlastnikJmeno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VlastnikTelefon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("VykonKw")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Vyrobce")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VyrobniCislo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "VyrobniCislo");

                    b.ToTable("Kotle");
                });

            modelBuilder.Entity("AzKotle.Core.Entities.ServisniZprava", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatumDalsihoServisu")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumZasahu")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Doporuceni")
                        .HasColumnType("text");

                    b.Property<Guid>("KotelId")
                        .HasColumnType("uuid");

                    b.Property<string>("PopisUkonu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Technik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Zavady")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KotelId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "KotelId", "DatumZasahu");

                    b.ToTable("ServisniZpravy");
                });

            modelBuilder.Entity("AzKotle.Core.Entities.ServisniZprava", b =>
                {
                    b.HasOne("AzKotle.Core.Entities.Kotel", "Kotel")
                        .WithMany("ServisniZpravy")
                        .HasForeignKey("KotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kotel");
                });

            modelBuilder.Entity("AzKotle.Core.Entities.Kotel", b =>
                {
                    b.Navigation("ServisniZpravy");
                });
#pragma warning restore 612, 618
        }
    }
}
